# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
sudo: false
matrix:
  include:
  - python: '2.7'
  - python: '3.6'
  - python: '3.7'
  - python: 'pypy'
    dist: trusty

before_install:
  - pip install -U pip

install:
  - pip install -U -r requirements.txt

before_script:
  - flake8 .

script: pytest

after_success: coveralls
