dist: xenial
language: python
sudo: false
matrix:
  include:
  - python: '3.5'
  - python: '3.6'
  - python: '3.7'
  - python: '3.8'
  - python: pypy3
    dist: trusty
before_install:
- pip install -U pip
install:
- pip install -U -r requirements.txt
before_script:
- flake8 .
script: pytest
after_success: coveralls
