# Config file for automatic testing at travis-ci.org

language: python
sudo: false
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

before_install:
  - pip install -U pip

install:
  - pip install -U -r requirements.txt

before_script:
  - flake8 .

script: py.test tests --cov=marshmallow_polyfield

after_success: coveralls
